# Generated by Django 5.2 on 2025-05-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0003_customuser_department_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='switches',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overlay',
            name='topology',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
