# Generated by Django 5.2 on 2025-05-30 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0004_overlay_switches_overlay_topology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='status',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='switches',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='topology',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='user',
        ),
        migrations.AddField(
            model_name='overlay',
            name='configuration',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='overlay',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.CreateModel(
            name='DemandeOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('configuration', models.JSONField()),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
