# Generated by Django 5.2 on 2025-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0006_overlay_status_overlay_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='overlay',
            name='tunnel_mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='overlay',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
