# Generated by Django 5.2 on 2025-06-02 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0009_alter_notification_demand_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderlayNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switches', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlay_networks', to='networkapp.overlay')),
            ],
        ),
    ]
