# Generated by Django 5.2 on 2025-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkapp', '0010_underlaynetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='underlaynetwork',
            name='config_scripts',
            field=models.JSONField(default=dict),
        ),
    ]
